/**
 * [오늘 뭐 볼까?] - 확장 통합 데이터베이스 모듈 (data.js)
 * 
 * 총 60편 이상의 최고 인기 명작 영화 및 웹툰의 장르, 감성/분위기 태그, 줄거리 핵심 키워드 메타데이터를 관리합니다.
 * 실제 서비스 운영 시 오픈 API(TMDB, KOBIS, 네이버/카카오 웹툰 API 등)와 연동할 수 있도록
 * 표준화된 데이터 구조를 갖추고 있습니다.
 */

// 영화 및 웹툰 통합 데이터베이스 (총 60편 대규모 데이터셋)
const CONTENT_DATABASE = [
    // =========================================================================
    // 🎬 영화 데이터베이스 (Movies - 총 30편)
    // =========================================================================
    {
        id: "m1",
        type: "movie",
        title: "인셉션 (Inception)",
        category: "SF / 스릴러",
        releaseYear: 2010,
        rating: 9.6,
        poster: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
        summary: "타인의 꿈에 들어가 생각을 훔치거나 심는 특수 요원 코브의 마지막 미션과 시공간을 넘나드는 무의식의 세계.",
        genres: ["SF", "스릴러", "액션", "미스터리"],
        moodTags: ["#두뇌싸움", "#몰입감최고", "#반전", "#압도적스케일", "#심리전"],
        keywords: ["꿈", "무의식", "기억", "시간", "시공간", "미션", "설계", "스파이", "추리", "팽이", "현실"]
    },
    {
        id: "m2",
        type: "movie",
        title: "인터스텔라 (Interstellar)",
        category: "SF / 드라마",
        releaseYear: 2014,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
        summary: "황폐해진 지구를 떠나 인류의 새로운 터전을 찾기 위해 우주 웜홀로 떠나는 탐사 대원들의 장대한 여정과 가족애.",
        genres: ["SF", "드라마", "어드벤처"],
        moodTags: ["#압도적스케일", "#감동", "#눈물샘자극", "#몰입감최고", "#가족"],
        keywords: ["우주", "웜홀", "블랙홀", "시간", "상대성이론", "가족", "부녀", "지구", "생존", "탐사", "희망"]
    },
    {
        id: "m3",
        type: "movie",
        title: "어바웃 타임 (About Time)",
        category: "로맨스 / 판타지",
        releaseYear: 2013,
        rating: 9.3,
        poster: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
        summary: "성인이 되자마자 시간 여행 능력이 있다는 가문의 비밀을 알게 된 팀이 진정한 사랑과 인생의 소중함을 깨달아가는 이야기.",
        genres: ["로맨스", "코미디", "판타지", "드라마"],
        moodTags: ["#힐링", "#인생명작", "#가슴따뜻한", "#설렘", "#감동"],
        keywords: ["시간여행", "타임슬립", "사랑", "결혼", "가족", "아버지", "일상", "행복", "후회없는삶", "인생"]
    },
    {
        id: "m4",
        type: "movie",
        title: "기생충 (Parasite)",
        category: "드라마 / 스릴러 / 블랙코미디",
        releaseYear: 2019,
        rating: 9.5,
        poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
        summary: "전원 백수로 살길이 막막한 기택 가족의 장남 기우가 박 사장네 고액 과외 면접을 보러 가면서 시작되는 걷잡을 수 없는 사건.",
        genres: ["드라마", "스릴러", "코미디", "서스펜스"],
        moodTags: ["#몰입감최고", "#반전", "#현실풍자", "#긴장감폭발", "#충격"],
        keywords: ["빈부격차", "계급", "가족", "거짓말", "비밀", "지하실", "계획", "파국", "사회비판", "냄새"]
    },
    {
        id: "m5",
        type: "movie",
        title: "라라랜드 (La La Land)",
        category: "뮤지컬 / 로맨스",
        releaseYear: 2016,
        rating: 9.1,
        poster: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
        summary: "꿈을 꾸는 사람들을 위한 도시 LA에서 만난 재즈 피아니스트 세바스찬과 배우 지망생 미아의 열정과 애틋한 사랑.",
        genres: ["뮤지컬", "로맨스", "드라마"],
        moodTags: ["#감성자극", "#여운이남는", "#음악맛집", "#설렘", "#인생명작"],
        keywords: ["꿈", "열정", "재즈", "배우", "사랑", "이별", "현실", "계절", "음악", "LA", "낭만"]
    },
    {
        id: "m6",
        type: "movie",
        title: "다크 나이트 (The Dark Knight)",
        category: "액션 / 범죄 / 스릴러",
        releaseYear: 2008,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
        summary: "정의를 지키려는 배트맨과 도시를 혼돈에 빠뜨리려는 조커 사이의 피할 수 없는 치열한 신념의 대결.",
        genres: ["액션", "범죄", "스릴러", "드라마"],
        moodTags: ["#두뇌싸움", "#다크판타지", "#긴장감폭발", "#몰입감최고", "#사이다"],
        keywords: ["정의", "악", "조커", "배트맨", "도시", "혼돈", "선택", "심리전", "신념", "히어로", "범죄"]
    },
    {
        id: "m7",
        type: "movie",
        title: "너의 이름은. (Your Name)",
        category: "애니메이션 / 판타지 / 로맨스",
        releaseYear: 2017,
        rating: 9.4,
        poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
        summary: "도쿄의 소년 타키와 시골의 소녀 미츠하의 몸이 서로 뒤바뀌는 신비한 꿈과 혜성을 둘러싼 운명적인 시공간의 기적.",
        genres: ["애니메이션", "로맨스", "판타지", "드라마"],
        moodTags: ["#감동", "#눈물샘자극", "#여운이남는", "#영상미", "#설렘"],
        keywords: ["몸바뀜", "시간", "혜성", "운명", "기억", "인연", "재난", "구원", "도쿄", "황혼"]
    },
    {
        id: "m8",
        type: "movie",
        title: "존 윅 (John Wick)",
        category: "액션 / 스릴러 / 범죄",
        releaseYear: 2014,
        rating: 9.0,
        poster: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        summary: "전설적인 킬러 존 윅이 사랑하는 아내가 남긴 마지막 선물을 빼앗긴 후 시작되는 거침없고 통쾌한 복수극.",
        genres: ["액션", "범죄", "스릴러"],
        moodTags: ["#사이다", "#액션쾌감", "#몰입감최고", "#스피디한전개", "#킬러"],
        keywords: ["복수", "킬러", "총격전", "암살자", "강아지", "지하세계", "룰", "원샷원킬", "분노"]
    },
    {
        id: "m9",
        type: "movie",
        title: "쇼생크 탈출 (The Shawshank Redemption)",
        category: "드라마 / 범죄",
        releaseYear: 1994,
        rating: 9.9,
        poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
        summary: "억울한 누명을 쓰고 악명 높은 쇼생크 교도소에 수감된 앤디 듀프레인이 희망을 잃지 않고 자유를 향해 나아가는 위대한 탈출기.",
        genres: ["드라마", "범죄"],
        moodTags: ["#인생명작", "#감동", "#두뇌싸움", "#사이다", "#여운이남는"],
        keywords: ["희망", "자유", "탈옥", "교도소", "우정", "인내", "회계", "누명", "인간승리"]
    },
    {
        id: "m10",
        type: "movie",
        title: "아바타 (Avatar)",
        category: "SF / 판타지 / 액션",
        releaseYear: 2009,
        rating: 9.3,
        poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
        summary: "신비로운 판도라 행성에서 나비족의 몸으로 의식을 연결한 전직 해병대원 제이크 설리가 행성의 운명을 건 선택을 하는 SF 대서사시.",
        genres: ["SF", "판타지", "액션", "모험"],
        moodTags: ["#압도적스케일", "#영상미", "#몰입감최고", "#설렘", "#액션쾌감"],
        keywords: ["판도라", "외계행성", "아바타", "교감", "자연", "전쟁", "의식연결", "비행", "혁명"]
    },
    {
        id: "m11",
        type: "movie",
        title: "어벤져스: 엔드게임 (Avengers: Endgame)",
        category: "액션 / SF / 판타지",
        releaseYear: 2019,
        rating: 9.6,
        poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
        summary: "타노스의 핑거스냅 이후 절반만 남은 세상을 되돌리기 위해 시간여행 작전을 펼치는 어벤져스의 마지막 총력전.",
        genres: ["액션", "SF", "판타지", "모험"],
        moodTags: ["#압도적스케일", "#감동", "#사이다", "#눈물샘자극", "#액션쾌감"],
        keywords: ["히어로", "시간여행", "타임슬립", "타노스", "아이언맨", "우주", "희생", "동료", "어벤져스"]
    },
    {
        id: "m12",
        type: "movie",
        title: "오펜하이머 (Oppenheimer)",
        category: "드라마 / 역사 / 스릴러",
        releaseYear: 2023,
        rating: 9.2,
        poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
        summary: "세상을 영원히 바꾼 맨해튼 프로젝트와 원자폭탄의 아버지 J. 로버트 오펜하이머의 찬란한 고뇌와 청문회의 비극.",
        genres: ["드라마", "역사", "스릴러", "전기"],
        moodTags: ["#두뇌싸움", "#심리전", "#긴장감폭발", "#몰입감최고", "#인생명작"],
        keywords: ["원자폭탄", "과학자", "물리학", "전쟁", "청문회", "고뇌", "정치", "역사", "천재", "양심"]
    },
    {
        id: "m13",
        type: "movie",
        title: "서울의 봄 (12.12: The Day)",
        category: "드라마 / 스릴러 / 역사",
        releaseYear: 2023,
        rating: 9.6,
        poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
        summary: "1979년 12월 12일 수도 서울에서 일어난 신군부 세력의 반란을 막기 위한 일촉즉발의 9시간 숨 막히는 군사 대결.",
        genres: ["드라마", "스릴러", "역사", "정치"],
        moodTags: ["#긴장감폭발", "#몰입감최고", "#심리전", "#두뇌싸움", "#현실풍자"],
        keywords: ["군사반란", "신군부", "수도경비", "군인", "권력", "정치", "역사", "대치", "실화"]
    },
    {
        id: "m14",
        type: "movie",
        title: "올드보이 (Oldboy)",
        category: "스릴러 / 미스터리 / 액션",
        releaseYear: 2003,
        rating: 9.4,
        poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
        summary: "이유도 모른 채 15년간 사설 감옥에 갇혀 있던 오대수가 풀려난 뒤 자신을 가둔 자를 찾아 추적하는 충격적인 복수극.",
        genres: ["스릴러", "미스터리", "액션", "범죄"],
        moodTags: ["#반전", "#충격", "#다크판타지", "#긴장감폭발", "#몰입감최고"],
        keywords: ["감금", "복수", "비밀", "최면", "장도리", "진실", "기억", "파멸", "비극"]
    },
    {
        id: "m15",
        type: "movie",
        title: "엘리멘탈 (Elemental)",
        category: "애니메이션 / 판타지 / 로맨스",
        releaseYear: 2023,
        rating: 9.3,
        poster: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
        summary: "불, 물, 공기, 흙 4개 원소가 살아가는 엘리멘트 시티에서 열정 넘치는 앰버와 감성적인 웨이드가 만나 피어나는 특별한 사랑 이야기.",
        genres: ["애니메이션", "판타지", "로맨스", "코미디"],
        moodTags: ["#힐링", "#감동", "#설렘", "#가슴따뜻한", "#눈물샘자극"],
        keywords: ["원소", "불", "물", "사랑", "다름", "이해", "가족", "성장", "도시", "희망"]
    },
    {
        id: "m16",
        type: "movie",
        title: "헤어질 결심 (Decision to Leave)",
        category: "미스터리 / 로맨스 / 드라마",
        releaseYear: 2022,
        rating: 9.1,
        poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
        summary: "산 정상에서 추락한 남자의 변사 사건을 맡은 형사 해준이 사망자의 아내 서래를 조사하며 시작되는 미묘한 의심과 관심.",
        genres: ["미스터리", "로맨스", "드라마", "스릴러"],
        moodTags: ["#여운이남는", "#심리전", "#감성자극", "#몰입감최고", "#인생명작"],
        keywords: ["형사", "용의자", "살인", "사랑", "바다", "안개", "녹음", "비밀", "미결"]
    },
    {
        id: "m17",
        type: "movie",
        title: "극한직업 (Extreme Job)",
        category: "코미디 / 액션 / 범죄",
        releaseYear: 2019,
        rating: 9.3,
        poster: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        summary: "해체 위기의 마약반 5인방이 범죄조직 소탕을 위해 위장 창업한 마약치킨집이 일약 맛집으로 대박 나면서 벌어지는 코믹 수사극.",
        genres: ["코미디", "액션", "범죄"],
        moodTags: ["#유쾌함", "#사이다", "#액션쾌감", "#스피디한전개", "#몰입감최고"],
        keywords: ["치킨집", "마약반", "형사", "위장수사", "맛집", "범죄소탕", "웃음", "팀워크"]
    },
    {
        id: "m18",
        type: "movie",
        title: "위플래쉬 (Whiplash)",
        category: "드라마 / 음악",
        releaseYear: 2014,
        rating: 9.4,
        poster: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
        summary: "최고의 재즈 드러머가 되고 싶은 열망을 품은 신입생 앤드류와 그의 한계를 극한까지 몰아붙이는 폭군 교수 플레처의 광기 어린 집착.",
        genres: ["드라마", "음악", "스릴러"],
        moodTags: ["#긴장감폭발", "#몰입감최고", "#광기", "#음악맛집", "#인생명작"],
        keywords: ["드럼", "재즈", "광기", "완벽주의", "스승", "제자", "집착", "한계", "카타르시스"]
    },
    {
        id: "m19",
        type: "movie",
        title: "조커 (Joker)",
        category: "드라마 / 범죄 / 스릴러",
        releaseYear: 2019,
        rating: 9.3,
        poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
        summary: "고담시의 광대로 살아가며 웃음을 주고 싶었던 아서 플렉이 사회의 외면과 조롱 속에 광기의 화신 조커로 변해가는 과정.",
        genres: ["드라마", "범죄", "스릴러"],
        moodTags: ["#충격", "#다크판타지", "#심리전", "#여운이남는", "#몰입감최고"],
        keywords: ["광대", "아서플렉", "조커", "고담", "정신질환", "소외", "사회비판", "계단춤", "폭동"]
    },
    {
        id: "m20",
        type: "movie",
        title: "스파이더맨: 뉴 유니버스 (Spider-Man: Into the Spider-Verse)",
        category: "애니메이션 / 액션 / SF",
        releaseYear: 2018,
        rating: 9.6,
        poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
        summary: "새로운 10대 스파이더맨 마일스 모랄레스가 다차원의 평행우주에서 온 다양한 스파이더맨들과 팀을 이뤄 세계를 구하는 혁신적 애니메이션.",
        genres: ["애니메이션", "액션", "SF", "모험"],
        moodTags: ["#영상미", "#성장물", "#액션쾌감", "#스피디한전개", "#압도적스케일"],
        keywords: ["스파이더맨", "멀티버스", "평행우주", "성장", "히어로", "카툰렌더링", "힙합", "도약"]
    },
    {
        id: "m21",
        type: "movie",
        title: "타이타닉 (Titanic)",
        category: "로맨스 / 드라마",
        releaseYear: 1997,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
        summary: "세계 최대의 호화 여객선 타이타닉호에서 운명처럼 만난 자유로운 영혼 잭과 귀족 여성 로즈의 영원히 잊혀지지 않는 애절한 사랑.",
        genres: ["로맨스", "드라마", "재난"],
        moodTags: ["#인생명작", "#눈물샘자극", "#감동", "#설렘", "#압도적스케일"],
        keywords: ["타이타닉", "침몰", "재난", "사랑", "신분차이", "바다", "희생", "운명", "명작"]
    },
    {
        id: "m22",
        type: "movie",
        title: "센과 치히로의 행방불명 (Spirited Away)",
        category: "애니메이션 / 판타지 / 모험",
        releaseYear: 2002,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
        summary: "돼지로 변해버린 부모님을 구하기 위해 신들의 온천장에서 일하게 된 소녀 치히로의 신비롭고 눈부신 환상 모험.",
        genres: ["애니메이션", "판타지", "모험", "성장"],
        moodTags: ["#힐링", "#영상미", "#인생명작", "#성장물", "#여운이남는"],
        keywords: ["온천장", "유바바", "하쿠", "가오나시", "신비", "마법", "기억", "성장", "용기"]
    },
    {
        id: "m23",
        type: "movie",
        title: "범죄도시 (The Outlaws)",
        category: "액션 / 범죄",
        releaseYear: 2017,
        rating: 9.2,
        poster: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        summary: "괴물형사 마석도와 금천서 강력반이 하얼빈에서 넘어와 도시를 공포로 물들인 신흥 범죄조직 장첸 일당을 단숨에 일망타진하는 원펀치 액션.",
        genres: ["액션", "범죄"],
        moodTags: ["#사이다", "#액션쾌감", "#먼치킨", "#유쾌함", "#몰입감최고"],
        keywords: ["괴물형사", "마석도", "장첸", "주먹액션", "조폭소탕", "통쾌", "원펀치", "사이다"]
    },
    {
        id: "m24",
        type: "movie",
        title: "매트릭스 (The Matrix)",
        category: "SF / 액션",
        releaseYear: 1999,
        rating: 9.5,
        poster: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
        summary: "인간이 인공지능 기계의 에너지원으로 사육되며 가상현실 '매트릭스' 속에 살고 있다는 진실을 깨달은 해커 네오의 구원자로서의 각성.",
        genres: ["SF", "액션", "사이버펑크"],
        moodTags: ["#두뇌싸움", "#압도적스케일", "#액션쾌감", "#먼치킨", "#인생명작"],
        keywords: ["가상현실", "빨간약", "파란약", "인공지능", "해커", "네오", "모피어스", "총격전", "각성"]
    },
    {
        id: "m25",
        type: "movie",
        title: "코코 (Coco)",
        category: "애니메이션 / 판타지 / 음악",
        releaseYear: 2017,
        rating: 9.5,
        poster: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
        summary: "뮤지션을 꿈꾸는 소년 미구엘이 우연히 '죽은 자들의 세상'으로 들어가 숨겨진 가족의 비밀을 풀어나가는 가슴 뭉클한 음악 여행.",
        genres: ["애니메이션", "판타지", "음악", "가족"],
        moodTags: ["#감동", "#눈물샘자극", "#힐링", "#음악맛집", "#가족"],
        keywords: ["사후세계", "죽은자의날", "기억", "가족", "기타", "노래", "조상", "리멤버미"]
    },
    {
        id: "m26",
        type: "movie",
        title: "포레스트 검프 (Forrest Gump)",
        category: "드라마 / 코미디 / 로맨스",
        releaseYear: 1994,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
        summary: "조금은 남들과 다르지만 순수한 마음으로 달리는 포레스트 검프가 현대사의 굵직한 순간들을 관통하며 써내려가는 따뜻한 인생 감동극.",
        genres: ["드라마", "코미디", "로맨스"],
        moodTags: ["#인생명작", "#힐링", "#감동", "#가슴따뜻한", "#여운이남는"],
        keywords: ["달리기", "초콜릿상자", "순수", "사랑", "미국역사", "탁구", "새우잡이", "희망"]
    },
    {
        id: "m27",
        type: "movie",
        title: "엑시트 (EXIT)",
        category: "액션 / 코미디 / 재난",
        releaseYear: 2019,
        rating: 9.0,
        poster: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        summary: "도심 전체가 유독가스로 뒤덮인 전대미문의 재난 상황 속에서 대학교 산악동아리 출신 청년 백수 용남과 의주가 펼치는 탈출 생존기.",
        genres: ["액션", "코미디", "재난"],
        moodTags: ["#유쾌함", "#스피디한전개", "#사이다", "#긴장감폭발", "#몰입감최고"],
        keywords: ["유독가스", "클라이밍", "탈출", "옥상", "청년백수", "재난", "생존", "웃음"]
    },
    {
        id: "m28",
        type: "movie",
        title: "그랜드 부다페스트 호텔 (The Grand Budapest Hotel)",
        category: "코미디 / 모험 / 미스터리",
        releaseYear: 2014,
        rating: 9.2,
        poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
        summary: "세계 최고 호텔의 전설적인 지배인 구스타브와 로비보이 제로가 명화 도난 사건과 의문의 살인사건에 휘말리며 펼쳐지는 환상적인 모험.",
        genres: ["코미디", "모험", "미스터리", "드라마"],
        moodTags: ["#영상미", "#유쾌함", "#인생명작", "#감성자극", "#스피디한전개"],
        keywords: ["호텔", "지배인", "로비보이", "명화도난", "파스텔톤", "미장센", "상속", "추리"]
    },
    {
        id: "m29",
        type: "movie",
        title: "탑건: 매버릭 (Top Gun: Maverick)",
        category: "액션 / 드라마",
        releaseYear: 2022,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
        summary: "전설적인 파일럿 매버릭이 비밀 임무를 위해 최정예 탑건 파일럿들을 훈련시키며 극한의 공중전을 펼치는 압도적 전투기 액션.",
        genres: ["액션", "드라마"],
        moodTags: ["#액션쾌감", "#압도적스케일", "#사이다", "#감동", "#몰입감최고"],
        keywords: ["전투기", "파일럿", "탑건", "매버릭", "비행", "공중전", "스피드", "팀워크"]
    },
    {
        id: "m30",
        type: "movie",
        title: "겨울왕국 (Frozen)",
        category: "애니메이션 / 뮤지컬 / 판타지",
        releaseYear: 2013,
        rating: 9.2,
        poster: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
        summary: "모든 것을 얼려버리는 마법을 가진 언니 엘사와 그녀를 구하고 왕국의 봄을 되찾기 위해 모험을 떠나는 동생 안나의 자매애.",
        genres: ["애니메이션", "뮤지컬", "판타지", "모험"],
        moodTags: ["#음악맛집", "#감동", "#영상미", "#가족", "#설렘"],
        keywords: ["눈", "얼음마법", "엘사", "안나", "올라프", "자매애", "렛잇고", "왕국", "진정한사랑"]
    },

    // =========================================================================
    // 📱 웹툰 데이터베이스 (Webtoons - 총 30편)
    // =========================================================================
    {
        id: "w1",
        type: "webtoon",
        title: "전지적 독자 시점",
        category: "판타지 / 액션",
        releaseYear: 2020,
        rating: 9.9,
        poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80",
        summary: "10년 동안 연재된 소설이 완결되던 날, 소설 속 멸망한 세계가 현실이 되고 오직 결말을 아는 유일한 독자 김독자의 생존기.",
        genres: ["판타지", "액션", "SF", "모험"],
        moodTags: ["#사이다", "#두뇌싸움", "#몰입감최고", "#성장물", "#다크판타지"],
        keywords: ["소설", "성좌", "시나리오", "생존", "독자", "회귀", "배후성", "종말", "동료", "스킬", "전략"]
    },
    {
        id: "w2",
        type: "webtoon",
        title: "나 혼자만 레벨업",
        category: "판타지 / 액션",
        releaseYear: 2018,
        rating: 9.9,
        poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
        summary: "인류 최약병기로 불리던 E급 헌터 성진우가 의문의 퀘스트 창을 보게 되며 전 세계 유일하게 레벨업하는 그림자 군주로 각성하는 이야기.",
        genres: ["판타지", "액션", "모험"],
        moodTags: ["#사이다", "#먼치킨", "#액션쾌감", "#스피디한전개", "#압도적스케일"],
        keywords: ["헌터", "던전", "게이트", "레벨업", "퀘스트", "각성", "그림자", "군주", "원탑", "괴수"]
    },
    {
        id: "w3",
        type: "webtoon",
        title: "화산귀환",
        category: "무협 / 액션 / 코미디",
        releaseYear: 2021,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=600&q=80",
        summary: "천하삼대검수 매화검존 청명이 백 년 후 망해버린 화산파의 어린아이로 환생하여 문파를 다시 천하제일로 재건하는 유쾌통쾌 무협 활극.",
        genres: ["무협", "액션", "코미디", "환생"],
        moodTags: ["#사이다", "#유쾌함", "#먼치킨", "#성장물", "#몰입감최고"],
        keywords: ["환생", "무협", "화산파", "매화검존", "도문", "문파재건", "참교육", "사형제", "검술", "스승"]
    },
    {
        id: "w4",
        type: "webtoon",
        title: "유미의 세포들",
        category: "로맨스 / 일상 / 코미디",
        releaseYear: 2015,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=600&q=80",
        summary: "30대 직장인 유미의 머릿속에서 살아 숨 쉬는 개성 넘치는 세포들의 시각으로 그려낸 유쾌하고 공감 가득한 연애와 일상 성장기.",
        genres: ["로맨스", "일상", "코미디", "드라마"],
        moodTags: ["#힐링", "#공감백배", "#설렘", "#유쾌함", "#인생명작"],
        keywords: ["세포", "뇌", "연애", "직장인", "자아", "사랑", "성장", "공감", "음식", "이별", "일상"]
    },
    {
        id: "w5",
        type: "webtoon",
        title: "스위트홈",
        category: "스릴러 / 공포 / 액션",
        releaseYear: 2017,
        rating: 9.6,
        poster: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
        summary: "은둔형 외톨이 고등학생 현수가 가족을 잃고 이사 간 아파트에서 욕망으로 인해 괴물이 되어버린 사람들과 맞닥뜨리며 벌어지는 아포칼립스 스릴러.",
        genres: ["스릴러", "공포", "액션", "판타지"],
        moodTags: ["#긴장감폭발", "#다크판타지", "#몰입감최고", "#생존", "#충격"],
        keywords: ["괴물", "욕망", "아파트", "생존", "변이", "인간성", "고립", "절망", "희망", "재난"]
    },
    {
        id: "w6",
        type: "webtoon",
        title: "재혼 황후",
        category: "로맨스판타지 / 드라마",
        releaseYear: 2019,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
        summary: "완벽한 황후 나비에가 바람난 황제에게 이혼을 요구받고, 당당하게 옆 나라 황제와의 재혼을 선언하며 펼쳐지는 사이다 궁중 로맨스 판타지.",
        genres: ["로맨스판타지", "드라마", "판타지"],
        moodTags: ["#사이다", "#궁중암투", "#걸크러쉬", "#설렘", "#몰입감최고"],
        keywords: ["황후", "황제", "재혼", "이혼", "궁중", "복수", "당당함", "사랑", "정치", "귀족"]
    },
    {
        id: "w7",
        type: "webtoon",
        title: "머니게임 & 파이게임",
        category: "스릴러 / 드라마 / 심리",
        releaseYear: 2018,
        rating: 9.5,
        poster: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80",
        summary: "상금이 걸린 밀실 스튜디오에서 시간과 물품 구매 가격의 룰을 지키며 벌어지는 인간 군상의 적나라한 탐욕과 심리 서바이벌.",
        genres: ["스릴러", "드라마", "서바이벌"],
        moodTags: ["#두뇌싸움", "#심리전", "#현실풍자", "#긴장감폭발", "#인간본성"],
        keywords: ["서바이벌", "상금", "밀실", "규칙", "배신", "돈", "시간", "인간성", "정치", "게임"]
    },
    {
        id: "w8",
        type: "webtoon",
        title: "신의 탑",
        category: "판타지 / 모험 / 액션",
        releaseYear: 2010,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
        summary: "자신의 모든 것이었던 소녀 라헬을 찾기 위해 탑에 들어온 소년 밤과 탑의 정상을 향해 올라가는 수많은 선별인원들의 거대한 모험.",
        genres: ["판타지", "모험", "액션", "미스터리"],
        moodTags: ["#압도적스케일", "#두뇌싸움", "#성장물", "#반전", "#몰입감최고"],
        keywords: ["탑", "시험", "랭커", "신수", "포지션", "배신", "동료", "비선별인원", "비밀", "가문"]
    },
    {
        id: "w9",
        type: "webtoon",
        title: "외모지상주의",
        category: "학원 / 액션 / 드라마",
        releaseYear: 2014,
        rating: 9.5,
        poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
        summary: "괴롭힘을 당하던 뚱뚱하고 못생긴 고등학생 박형석이 완벽한 외모와 피지컬을 가진 두 번째 몸을 얻게 되며 벌어지는 크루 대전과 학원 액션.",
        genres: ["학원", "액션", "드라마"],
        moodTags: ["#사이다", "#액션쾌감", "#먼치킨", "#두뇌싸움", "#스피디한전개"],
        keywords: ["이중몸", "학원액션", "4대크루", "격투", "외모", "성장", "비밀", "복싱", "일진"]
    },
    {
        id: "w10",
        type: "webtoon",
        title: "가비지타임 (Garbage Time)",
        category: "스포츠 / 학원 / 성장",
        releaseYear: 2019,
        rating: 9.9,
        poster: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=600&q=80",
        summary: "선수가 부족해 폐부 위기에 놓인 지상고등학교 농구부에 새로운 코치가 부임하며 기적 같은 승리를 향해 나아가는 뜨거운 청춘 스포츠 만화.",
        genres: ["스포츠", "학원", "성장", "드라마"],
        moodTags: ["#성장물", "#감동", "#공감백배", "#인생명작", "#몰입감최고"],
        keywords: ["농구", "고교농구", "전술", "팀워크", "성장", "열정", "청춘", "패스", "슛"]
    },
    {
        id: "w11",
        type: "webtoon",
        title: "광마회귀 (Return of the Mad Demon)",
        category: "무협 / 액션 / 코미디",
        releaseYear: 2021,
        rating: 9.9,
        poster: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=600&q=80",
        summary: "무공에 미친 미치광이 광마 이자하가 죽기 전 천옥을 삼키고 과거 점소이 시절로 회귀하여 펼치는 예측불허 광기의 무협 활극.",
        genres: ["무협", "액션", "코미디", "회귀"],
        moodTags: ["#사이다", "#광기", "#유쾌함", "#먼치킨", "#액션쾌감"],
        keywords: ["회귀", "무협", "광마", "이자하", "점소이", "하오문", "참교육", "말빨", "무공"]
    },
    {
        id: "w12",
        type: "webtoon",
        title: "타인은 지옥이다",
        category: "스릴러 / 공포 / 미스터리",
        releaseYear: 2018,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
        summary: "상경한 시골 청년 윤종우가 돈이 없어 들어간 낡은 에덴고시원에서 마주친 기괴하고 섬뜩한 이웃들과의 숨 막히는 심리 공포.",
        genres: ["스릴러", "공포", "미스터리"],
        moodTags: ["#긴장감폭발", "#심리전", "#충격", "#다크판타지", "#몰입감최고"],
        keywords: ["고시원", "살인마", "밀실", "광기", "의심", "이웃", "고립", "공포", "파멸"]
    },
    {
        id: "w13",
        type: "webtoon",
        title: "바른연애 길잡이",
        category: "로맨스 / 일상 / 청춘",
        releaseYear: 2018,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
        summary: "철저한 계획표대로만 살아가던 대학생 정바름이 게임 개발 동아리에 들어가며 시작되는 두근두근 풋풋한 캠퍼스 로맨스.",
        genres: ["로맨스", "일상", "청춘", "드라마"],
        moodTags: ["#설렘", "#힐링", "#가슴따뜻한", "#공감백배", "#유쾌함"],
        keywords: ["캠퍼스", "동아리", "연애", "플래너", "게임개발", "선배", "남사친", "고백"]
    },
    {
        id: "w14",
        type: "webtoon",
        title: "나노마신 (Nano Machine)",
        category: "무협 / SF / 액션",
        releaseYear: 2020,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
        summary: "마교의 사생아 천여운이 미래의 후손에게 7세대 나노머신을 주입받고 무공을 스캔하며 마교 최강의 교주로 거듭나는 하이테크 무협.",
        genres: ["무협", "SF", "액션", "판타지"],
        moodTags: ["#사이다", "#먼치킨", "#액션쾌감", "#스피디한전개", "#두뇌싸움"],
        keywords: ["나노머신", "마교", "교주", "스캔", "치료", "사생아", "각성", "복수", "천마"]
    },
    {
        id: "w15",
        type: "webtoon",
        title: "치즈인더트랩 (Cheese in the Trap)",
        category: "로맨스 / 드라마 / 스릴러",
        releaseYear: 2010,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=600&q=80",
        summary: "평범한 여대생 홍설과 완벽해 보이지만 속을 알 수 없는 위험한 선배 유정 사이에서 벌어지는 숨 막히는 캠퍼스 로맨스릴러.",
        genres: ["로맨스", "드라마", "스릴러", "심리"],
        moodTags: ["#심리전", "#두뇌싸움", "#긴장감폭발", "#인생명작", "#설렘"],
        keywords: ["캠퍼스", "유정선배", "장학금", "인간관계", "심리싸움", "속마음", "연애", "의심"]
    },
    {
        id: "w16",
        type: "webtoon",
        title: "싸움독학",
        category: "학원 / 액션 / 성장",
        releaseYear: 2019,
        rating: 9.6,
        poster: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        summary: "학교 일진에게 시달리던 왜소한 유호빈이 의문의 쌈닭 유튜브 채널을 발견하고 실전 싸움 기술을 독학하여 인터넷 방송 스타로 성장하는 이야기.",
        genres: ["학원", "액션", "성장", "코미디"],
        moodTags: ["#사이다", "#성장물", "#액션쾌감", "#유쾌함", "#몰입감최고"],
        keywords: ["유튜브", "스트리밍", "싸움독학", "쌈닭", "카운터", "학원액션", "일진참교육", "성장"]
    },
    {
        id: "w17",
        type: "webtoon",
        title: "낮에 뜨는 달",
        category: "로맨스판타지 / 드라마 / 환생",
        releaseYear: 2013,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
        summary: "천오백 년 전 대가야 출신의 여인에게 살해당한 뒤 그녀의 주변을 맴도는 신라의 귀족 도하와 환생을 거듭하는 여인의 애절한 한과 사랑.",
        genres: ["로맨스판타지", "드라마", "환생", "미스터리"],
        moodTags: ["#여운이남는", "#눈물샘자극", "#감동", "#인생명작", "#다크판타지"],
        keywords: ["환생", "신라", "도하", "나으리", "원혼", "비극", "사랑", "애절함", "빙의"]
    },
    {
        id: "w18",
        type: "webtoon",
        title: "윈드브레이커 (Wind Breaker)",
        category: "스포츠 / 학원 / 청춘",
        releaseYear: 2013,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=600&q=80",
        summary: "자전거가 인생의 전부인 전교회장 조자현이 크루 '허밍버드' 멤버들과 함께 국내 최대 스트리트 자전거 대회 리그 스트리트에 도전하는 질주.",
        genres: ["스포츠", "학원", "액션", "청춘"],
        moodTags: ["#액션쾌감", "#스피디한전개", "#성장물", "#열정", "#몰입감최고"],
        keywords: ["자전거", "픽시", "다운힐", "스트리트", "크루", "우정", "라이딩", "속도"]
    },
    {
        id: "w19",
        type: "webtoon",
        title: "약한영웅 (Weak Hero)",
        category: "학원 / 액션 / 두뇌",
        releaseYear: 2018,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
        summary: "체격은 왜소하지만 천재적인 두뇌와 심리전, 도구를 활용하여 학교 폭력 일진들을 하나씩 제압해 나가는 연시은의 처절한 생존 학원 액션.",
        genres: ["학원", "액션", "두뇌"],
        moodTags: ["#두뇌싸움", "#사이다", "#심리전", "#긴장감폭발", "#몰입감최고"],
        keywords: ["두뇌액션", "도구활용", "연시은", "학교폭력", "일진", "심리전", "참교육", "은장고"]
    },
    {
        id: "w20",
        type: "webtoon",
        title: "템빨 (Overgeared)",
        category: "게임판타지 / 액션 / 코미디",
        releaseYear: 2020,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
        summary: "가상현실 게임 'SATISFY'에서 빚더미에 앉아 노가다만 하던 신영우가 전설의 대장장이 '파그마의 기서'를 얻으며 아이템의 힘으로 세계를 평정하는 이야기.",
        genres: ["게임판타지", "액션", "코미디"],
        moodTags: ["#먼치킨", "#사이다", "#성장물", "#유쾌함", "#압도적스케일"],
        keywords: ["가상현실", "대장장이", "아이템", "그리드", "파그마", "제작", "길드", "퀘스트"]
    },
    {
        id: "w21",
        type: "webtoon",
        title: "김부장 (Manager Kim)",
        category: "액션 / 느와르 / 드라마",
        releaseYear: 2021,
        rating: 9.6,
        poster: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80",
        summary: "평범한 회사원 행세를 하던 전직 특수부대 블랙요원 김부장이 실종된 딸 민지를 찾기 위해 지하 범죄조직을 모조리 초토화시키는 원맨 액션.",
        genres: ["액션", "느와르", "범죄"],
        moodTags: ["#사이다", "#액션쾌감", "#먼치킨", "#가족", "#몰입감최고"],
        keywords: ["특수부대", "CQC", "딸바보", "국정원", "블랙요원", "복수", "조폭소탕", "무력"]
    },
    {
        id: "w22",
        type: "webtoon",
        title: "피라미드 게임",
        category: "학원 / 스릴러 / 심리",
        releaseYear: 2020,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80",
        summary: "한 달에 한 번 비밀투표로 합법적 왕따(F등급)를 뽑는 백연여고 2학년 5반에 전학 온 성수지가 잔혹한 서바이벌 서열 피라미드를 깨부수는 두뇌 싸움.",
        genres: ["학원", "스릴러", "심리", "서바이벌"],
        moodTags: ["#두뇌싸움", "#심리전", "#사이다", "#긴장감폭발", "#현실풍자"],
        keywords: ["서열", "투표", "왕따", "여고", "심리게임", "두뇌싸움", "전학생", "체제전복"]
    },
    {
        id: "w23",
        type: "webtoon",
        title: "마음의 소리",
        category: "일상 / 코미디 / 개그",
        releaseYear: 2006,
        rating: 9.9,
        poster: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=600&q=80",
        summary: "작가 조석과 그의 가족, 강아지들이 겪는 황당무계하고 예측불허한 일상을 독창적인 개그와 병맛 코드로 담아낸 대한민국 레전드 웹툰.",
        genres: ["일상", "코미디", "개그"],
        moodTags: ["#유쾌함", "#공감백배", "#인생명작", "#힐링", "#웃음"],
        keywords: ["조석", "애봉이", "센세이션", "일상개그", "병맛", "레전드", "웃음", "가족"]
    },
    {
        id: "w24",
        type: "webtoon",
        title: "캐슬 (Castle)",
        category: "느와르 / 액션 / 범죄",
        releaseYear: 2019,
        rating: 9.9,
        poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
        summary: "거대 범죄 카르텔 '캐슬'에 의해 스승과 아버지를 잃은 러시아 특수 킬러 김신이 복수를 위해 칼을 갈고 캐슬을 무너뜨리려는 정통 느와르 액션.",
        genres: ["느와르", "액션", "범죄"],
        moodTags: ["#긴장감폭발", "#액션쾌감", "#몰입감최고", "#다크판타지", "#두뇌싸움"],
        keywords: ["느와르", "칼잡이", "카르텔", "복수", "김신", "암살자", "러시아", "세력전"]
    },
    {
        id: "w25",
        type: "webtoon",
        title: "쌉니다 천리마마트",
        category: "코미디 / 드라마 / 풍자",
        releaseYear: 2011,
        rating: 9.8,
        poster: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=600&q=80",
        summary: "대마그룹의 유배지라 불리는 천리마마트를 망하게 하려는 천재 이사 정복동과 이를 기사회생시키려는 순진한 점장 문석구의 유쾌한 병맛 블랙코미디.",
        genres: ["코미디", "드라마", "풍자"],
        moodTags: ["#유쾌함", "#힐링", "#현실풍자", "#사이다", "#인생명작"],
        keywords: ["마트", "정복동", "빠야족", "블랙코미디", "풍자", "기사회생", "대마그룹", "감동"]
    },
    {
        id: "w26",
        type: "webtoon",
        title: "지옥 (Hellbound)",
        category: "스릴러 / 공포 / 미스터리",
        releaseYear: 2019,
        rating: 9.5,
        poster: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
        summary: "예고 없이 찾아오는 사자들에게 지옥행 고지를 받고 시연을 당하는 초자연적 현상 속에서 신흥 종교 '새진리회'와 진실을 밝히려는 자들의 충돌.",
        genres: ["스릴러", "공포", "미스터리", "판타지"],
        moodTags: ["#충격", "#다크판타지", "#긴장감폭발", "#몰입감최고", "#심리전"],
        keywords: ["지옥고지", "시연", "새진리회", "사이비", "초자연", "종말", "인간성", "단죄"]
    },
    {
        id: "w27",
        type: "webtoon",
        title: "소녀재판",
        category: "학원 / 스릴러 / 미스터리",
        releaseYear: 2020,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80",
        summary: "존재감 없이 살아가던 박가을이 학교 인기남 한유현의 치명적인 비밀을 목격한 후, 그를 조종하며 학교라는 작은 사회의 판도를 뒤흔드는 심리 서스펜스.",
        genres: ["학원", "스릴러", "미스터리", "심리"],
        moodTags: ["#심리전", "#두뇌싸움", "#긴장감폭발", "#몰입감최고", "#충격"],
        keywords: ["비밀", "조종", "가스라이팅", "학교", "서열", "약점", "심리전", "반전"]
    },
    {
        id: "w28",
        type: "webtoon",
        title: "세기말 풋사과 보습학원",
        category: "로맨스 / 학원 / 청춘",
        releaseYear: 2020,
        rating: 9.9,
        poster: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
        summary: "1999년 세기말, 덩치만 크고 퉁명스러운 소꿉친구 김철과 발랄하고 고집 센 황미애가 시골 학원에서 재회하며 벌어지는 몽글몽글 레트로 청춘 성장기.",
        genres: ["로맨스", "학원", "청춘", "일상"],
        moodTags: ["#설렘", "#힐링", "#공감백배", "#가슴따뜻한", "#유쾌함"],
        keywords: ["1999년", "세기말", "레트로", "소꿉친구", "김철", "보습학원", "중학교", "청춘"]
    },
    {
        id: "w29",
        type: "webtoon",
        title: "빌드업 (Build Up)",
        category: "스포츠 / 학원 / 코미디",
        releaseYear: 2020,
        rating: 9.7,
        poster: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=600&q=80",
        summary: "축구를 좋아하지만 소심한 벤치 신세였던 강마루가 정확한 롱패스와 넓은 시야를 무기로 전국 제패를 노리는 고교 축구 성장 만화.",
        genres: ["스포츠", "학원", "코미디", "성장"],
        moodTags: ["#성장물", "#유쾌함", "#열정", "#감동", "#사이다"],
        keywords: ["축구", "패스", "시야", "고교축구", "벤치", "성장", "팀워크", "스포츠"]
    },
    {
        id: "w30",
        type: "webtoon",
        title: "퀘스트지상주의",
        category: "학원 / 액션 / 판타지",
        releaseYear: 2021,
        rating: 9.5,
        poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
        summary: "학교 셔틀 김수현에게 어느 날 게임 퀘스트 창이 눈앞에 나타나고, 퀘스트를 완료하며 얻은 카드의 능력으로 강북을 통합해 나가는 학원 판타지 액션.",
        genres: ["학원", "액션", "판타지", "성장"],
        moodTags: ["#사이다", "#먼치킨", "#성장물", "#스피디한전개", "#액션쾌감"],
        keywords: ["퀘스트", "상태창", "카드스킬", "강북통합", "일진", "셔틀탈출", "레벨업", "학원물"]
    }
];

// 서비스에서 선택 가능한 추천 분위기/감성 태그 목록
const MOOD_TAG_OPTIONS = [
    "#두뇌싸움",
    "#몰입감최고",
    "#사이다",
    "#힐링",
    "#감동",
    "#눈물샘자극",
    "#반전",
    "#긴장감폭발",
    "#먼치킨",
    "#압도적스케일",
    "#다크판타지",
    "#설렘",
    "#공감백배",
    "#유쾌함",
    "#심리전",
    "#성장물",
    "#액션쾌감",
    "#인생명작"
];
